---
title: "Surface_Temperature_NOAA"
author: "Cindy Fajardo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.path = "../Output/")
```

# Libraries
```{r, Libraries}
library("rerddap")
library("tidyverse")
library("tidync")
library("doParallel")
library(lubridate)
library(patchwork)
library(viridis)
library(here)
library(kableExtra)
library(weathermetrics)
```

# NOAA Website
```{r, NOAA Website}
####This tells R to use NOAA designated website and what data set to use#####
rerddap::info(datasetid = "noaa_psl_675a_3cea_522e", url = "https://upwell.pfeg.noaa.gov/erddap")
```
# Pull SCI Data From NOAA
```{r, Pull SCI NOAA Data}
sci_surface_temp<-griddap(datasetx = "noaa_psl_675a_3cea_522e", 
                   url = "https://upwell.pfeg.noaa.gov/erddap", 
                   time = c("2020-01-01", "2022-12-31"),
                   latitude =  c(34.1,34.1),
                   longitude = c(240.1,240.1),
                   fields = "air")$data %>% 
  mutate(time = as.Date(stringr::str_remove(time, "T00:00:00Z")),
         air_c = kelvin.to.celsius(air)) %>% 
  select(longitude, latitude, time, air_c) %>% 
  na.omit()%>%
  mutate(month = month(time), # extract the month
         year = year(time),
         site = "Santa Cruz Island",
         season  = case_when( # make a season
           month %in% c(12,1,2) ~ "Winter",
           month %in% c(3,4,5) ~ "Spring",
           month %in% c(6,7,8) ~ "Summer",
           month %in% c(9,10,11) ~ "Fall"
         ),
         season = factor(season),
         season = fct_relevel(season, c("Winter","Spring","Summer","Fall")))
```

# Summarize SCI Data
```{r, Summarize SCI Data}
sci_surface_temp %>%
  group_by(year, season)%>%
  summarise(Temp.mean = mean(air_c, na.rm = TRUE),
            Temp.max = max(air_c, na.rm = TRUE),
            Temp.min = min(air_c, na.rm = TRUE)) %>% 
  kbl()%>% #make a table
  kable_styling(full_width = F, font_size = 15)
```

# Pull CNM Data From NOAA
```{r, Pull CNM Data}
cnm_surface_temp<-griddap(datasetx = "noaa_psl_675a_3cea_522e", 
                   url = "https://upwell.pfeg.noaa.gov/erddap", 
                   time = c("2020-01-01", "2022-12-31"),
                   latitude =  c(32.7,32.7),
                   longitude = c(242.8,242.8),
                   fields = "air")$data %>% 
  mutate(time = as.Date(stringr::str_remove(time, "T00:00:00Z")),
         air_c = kelvin.to.celsius(air)) %>% 
  select(longitude, latitude, time, air_c) %>% 
  na.omit()%>%
  mutate(month = month(time), # extract the month
         year = year(time),
         site = "Cabrillo National Monument",
         season  = case_when( # make a season
           month %in% c(12,1,2) ~ "Winter",
           month %in% c(3,4,5) ~ "Spring",
           month %in% c(6,7,8) ~ "Summer",
           month %in% c(9,10,11) ~ "Fall"
         ),
         season = factor(season),
         season = fct_relevel(season, c("Winter","Spring","Summer","Fall")))
```

# Summarize CNM Data
```{r, Summarize CNM Data}
cnm_surface_temp %>%
  filter(year <= 2022,
         year >=2020)%>% 
  group_by(year, season)%>%
  summarise(Temp.mean = mean(air_c, na.rm = TRUE),
            Temp.max = max(air_c, na.rm = TRUE),
            Temp.min = min(air_c, na.rm = TRUE)) %>% 
  kbl()%>% #make a table
  kable_styling(full_width = F, font_size = 15)
```

# SCI Line Graph
```{r}
sci_filtered_temp <- sci_surface_temp %>%
  filter(year <= 2022,
         year >=2020)

ggplot(sci_filtered_temp, # data used is the sci_surface_temp we created
       aes(x = time, #x axis is time
           y = air_c))+ #y axis is sea surface temperature
  labs(title = "Santa Cruz Island", #title
       x = "Year", # label for x axis
       y = "Aerial Surface Temperature, (C)", # label for y axis
       color = "Season")+ # legend label
  theme_bw()+
  geom_line()+ # draw a line graph
  geom_point(aes(color = season))+ # add points colored by seasons
  scale_color_manual(values = c("blue",
                                "green",
                                "red",
                                "orange"))
```

# CNM Line Graph
```{r, CNM Line Graph}
cnm_filtered_temp <- cnm_surface_temp %>%
  filter(year <= 2022,
         year >=2020)

ggplot(cnm_filtered_temp, # data used is the cnm_surface_temp we created
       aes(x = time, #x axis is time
           y = air_c))+ #y axis is sea surface temperature
  labs(title = "Cabrillo National Monument", #title
       x = "Year", # label for x axis
       y = "Aerial Surface Temperature, (C)", # label for y axis
       color = "Season")+ # legend label
  theme_bw()+
  geom_line()+ # draw a line graph
  geom_point(aes(color = season))+ # add points colored by seasons
  scale_color_manual(values = c("blue",
                                "green",
                                "red",
                                "orange"))
```

# CNM Box plot
```{r, cnm box plot}
c <- cnm_filtered_temp %>%
  ggplot(aes(x = as.factor(year), y = air_c, fill = season))+
  geom_boxplot()+
  labs(title = "Cabrillo National Monument",
       fill = "Season",
       x = "Year",
       y = "Sea Surface Temperature (C)")+
  theme(plot.title = element_text(size = 8),
        axis.title.y = element_text(size = 6),
        axis.title.x = element_text(size = 6),
        axis.text.x = element_text(size = 4),
        axis.text.y = element_text(size = 4))+
  scale_color_viridis_d(option = "D")

c
```

# SCI Box plot
```{r}
s <- sci_filtered_temp %>%
  ggplot(aes(x = as.factor(year), y = air_c, fill = season))+
  geom_boxplot()+
  labs(title = "Santa Cruz Island",
       fill = "Season",
       x = "Year",
       y = "Sea Surface Temperature (C)")+
  theme(plot.title = element_text(size = 8),
        axis.title.y = element_text(size = 6),
        axis.title.x = element_text(size = 6),
        axis.text.x = element_text(size = 4),
        axis.text.y = element_text(size = 4))+
  scale_color_viridis_d(option = "D")

s
```

# Both boxplots
```{r, both boxplot}
s/c+
  plot_layout(guides = 'collect')+
  plot_annotation(title = 'Average Aerial Surface Temperature per Season 2020-2022',
                  theme = theme(plot.title = element_text(size = 10)))
```

